name: flutter_remix_icon
description: Remix Icon for Flutter.
version: 4.2.0
homepage:

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
#  plugin:
#    platforms:
#      android:
#        package: africa.olorok.flutter_remix_icon
#        pluginClass: FlutterRemixIconPlugin
#      ios:
#        pluginClass: FlutterRemixIconPlugin

  fonts:
    - family: RemixIcon
      fonts:
        - asset: assets/fonts/remixicon.ttf
          style: normal

  assets:
    - assets/fonts/remixicon-glyph.json